### ISSUE TITLE
Add validation step against skohub.shacl.ttl

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-docker-vocabs#14]
If I interpret this correctly, there is currently no validation in the docker version against the skohub SHACL shape (https://github.com/skohub-io/shapes/blob/main/skohub.shacl.ttl).

Background: I just had some students trying to built their SKOS vocab with SkoHub and it did not work because `skos:hasTopConcept` was missing – though the inverse `skos:topConceptOf` is present. The was also validated as correct by https://skos-play.sparna.fr/skos-testing-tool/ . S0 they did a good job but were frustrated by SkoHub not building the vocab and not giving any error message as of why it would not build. 

(I built the vocab on the skohub.io server which helped me in finding the error as the server version validates against `skohub.shacl.tt` and, thus, I got back an error message.)

So we should:

1.) Add the validaton step to the docker version
2.) Also think about making it sufficient to use one of two inverse properties `skos:topConceptOf` or `skos:hasTopConcept`. (I think we already do this with `skos:broader`/`skos:barrower`, dont't we? We'd need another ticket for this in the skohub-vocabs repo. Edit: Here it is: https://github.com/skohub-io/skohub-vocabs/issues/289)

**Comment by sroertgen** [comment]
After starting to work on https://github.com/skohub-io/skohub-vocabs/issues/289 I noticed that we could skip the validation here at all since it is already validated in SkoHub Vocab and soon even better if we do validation after enrichment of skos:properties.
