### ISSUE TITLE
Can repository informations be provided via environment variables?

### ISSUE THREAD

**Issue by sroertgen** [skohub-io/skohub-docker-vocabs#17]

**Comment by sroertgen** [comment]
@acka47 I merged this into main.

Feel free to test.

Consider the following scenarios:

- someone forks this repo with the same name and modifies some vocabularies.
- someone changes the name of the repo when forking and modifies some vocabularies.

Both cases should work.

We use this issue to discuss further and will close it when everything is ok.

**Comment by sroertgen** [comment]
I shortened the usage section and added a troubleshooting section.

Regarding screenshots I'm hesitating since they blow up the size of the git repo.
Maybe we should put them somewhere different (like a tutorials repository) and just link them from there?

**Comment by sroertgen** [comment]
@acka47 so then close this now and I will make a new issue to add screenshots to the usage section.

**Comment by acka47** [comment]
> I think, we should just keep this in mind for implementing https://github.com/skohub-io/skohub.io/issues/19 (which will be done in a different repo than this, I think).

I've added it in https://github.com/skohub-io/skohub.io/issues/19#issuecomment-1997665715, feel free to close this one now.
