### ISSUE TITLE
Update docker version after redesign

### ISSUE THREAD

**Issue by acka47** [skohub-io/skohub-docker-vocabs#5]
Depends on https://github.com/skohub-io/skohub-vocabs/issues/201

**Comment by sroertgen** [comment]
Yes, the implemented docker build discussed in https://github.com/skohub-io/skohub-vocabs/issues/202 and implemented with https://github.com/skohub-io/skohub-vocabs/pull/204 will now lead to automagic updates of the container used in this repo
